% Create Parameters for ADC Channel
%
% Copyright Brian G. Shea (bshea@eng.ucsd.edu)
%
function addParameters(hRD, channelID, enabled, width)

switch(nargin)
    case 2
        enabled = true;
        width = 128;
    case 3
        width = 128;
    otherwise
        error("Invalid number of arguments: %d", nargin);
end

   if(enabled)
       enVal = 'true';
   else
       enVal = 'false';
   end
   
hRD.addParameter(...
    'ParameterID',   sprintf('adc%d_enable', channelID), ...
    'DisplayName',   sprintf('Enable ADC%d', channelID), ...
    'DefaultValue',  enVal, ...
    'ParameterType', hdlcoder.ParameterType.Dropdown, ...
    'Choice',        {'false', 'true'}...
    );

hRD.addParameter(...
    'ParameterID',   sprintf('adc%d_axis_mode', channelID), ...
    'DisplayName',   sprintf('ADC%d AXIS Mode', channelID), ...
    'DefaultValue',  'both', ...
    'ParameterType', hdlcoder.ParameterType.Dropdown, ...
    'Choice',        {'both', 'master only', 'slave only'}...
    );

hRD.addParameter(...
    'ParameterID',   sprintf('adc%d_axis_master_width', channelID), ...
    'DisplayName',   sprintf('ADC%d AXIS Master Width', channelID), ...
    'DefaultValue',  sprintf('%d', width), ...
    'ParameterType', hdlcoder.ParameterType.Dropdown, ...
    'Choice',        {'128'}...
    );

hRD.addParameter(...
    'ParameterID',   sprintf('adc%d_axis_slave_width', channelID), ...
    'DisplayName',   sprintf('ADC%d AXIS Slave Width', channelID), ...
    'DefaultValue',  sprintf('%d', width), ...
    'ParameterType', hdlcoder.ParameterType.Dropdown, ...
    'Choice',        {'8', '16', '32', '64', '128'}...
    );
