% Customize ADC Channel
%
% Copyright Brian G. Shea (bshea@eng.ucsd.edu)

function customize(hRD, channelID, config)
% hRD: current reference design registration object
% config: custom parameters of the current channel, in struct format

if(nargin ~= 3)
    error("Invalid number of parameters.")
end

if(config.Enabled)
    if(isfield(config, 'MasterEn') && config.MasterEn && isfield(config, 'SlaveEn') && config.SlaveEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d RE', channelID),...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_RE', channelID), ...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_RE', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth, ...
            'SlaveChannelDataWidth',    128);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d IM', channelID),...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_IM', channelID), ...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_IM', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth, ...
            'SlaveChannelDataWidth',    128);
    elseif (isfield(config, 'SlaveEn') && config.SlaveEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d RE', channelID),...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_RE', channelID), ...
            'SlaveChannelDataWidth',    128);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d IM', channelID),...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_IM', channelID), ...
            'SlaveChannelDataWidth',    128);
    elseif (isfield(config, 'MasterEn') && config.MasterEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d RE', channelID),...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_RE', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d IM', channelID),...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_IM', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth);
    end 
end