% Customize ADC Channel
%
% Copyright Brian G. Shea (bshea@eng.ucsd.edu)

function customize(hRD, channelID, config)
% hRD: current reference design registration object
% config: custom parameters of the current channel, in struct format

if(nargin ~= 3)
    error("Invalid number of parameters.")
end

if(config.Enabled)
    if(isfield(config, 'MasterEn') && config.MasterEn && isfield(config, 'SlaveEn') && config.SlaveEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d RE', channelID),...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_ADC_RE', channelID), ...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_ADC_RE', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth, ...
            'SlaveChannelDataWidth',    config.SlaveWidth);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d IM', channelID),...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_ADC_IM', channelID), ...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_ADC_IM', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth, ...
            'SlaveChannelDataWidth',    config.SlaveWidth);
        elseif (isfield(config, 'SlaveEn') && config.SlaveEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d RE', channelID),...
            'MasterChannelEnable',      false, ...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_ADC_RE', channelID), ...
            'SlaveChannelDataWidth',    config.SlaveWidth);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d IM', channelID),...
            'MasterChannelEnable',      false, ...
            'SlaveChannelConnection' ,  sprintf('radio/M%d0_AXIS_ADC_IM', channelID), ...
            'SlaveChannelDataWidth',    config.SlaveWidth);
    elseif (isfield(config, 'MasterEn') && config.MasterEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d RE', channelID),...
            'SlaveChannelEnable',       false, ...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_ADC_RE', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('ADC%d IM', channelID),...
            'SlaveChannelEnable',       false, ...
            'MasterChannelConnection',  sprintf('radio/S%d0_AXIS_ADC_IM', channelID), ...
            'MasterChannelDataWidth',   config.MasterWidth);
    end
    
    if(config.NCOEnabled)
        % Map RF ADCx Tile NCO Ports
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 NCO Frequency', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d_nco_freq', channelID), ...
            'PortWidth',           48, ...
            'InterfaceConnection', sprintf('radio/adc%d_nco_converter01_nco_freq', channelID) ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 NCO Phase', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d_nco_phase', channelID), ...
            'PortWidth',           18, ...
            'InterfaceConnection', sprintf('radio/adc%d_nco_converter01_nco_phase', channelID) ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 NCO Phase Reset', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d_nco_phase_reset', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_nco_converter01_phase_reset', channelID) ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 NCO Update Enable', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d_nco_update_en', channelID), ...
            'PortWidth',           6, ...
            'InterfaceConnection', sprintf('radio/adc%d_nco_converter01_update_en', channelID) ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d NCO Update Busy', channelID), ...
            'InterfaceType',       'IN', ...
            'PortName',            sprintf('adc%d_nco_update_busy', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_nco_nco_update_busy', channelID), ...
            'IsRequired',          false ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d NCO Update Request', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d_nco_update_request', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_nco_nco_update_request', channelID) ...
            );
    end

    if(config.RTSEnabled)
        % Map RF ADCx Tile RTS Ports
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 RTS PL Event out', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d0_pl_event', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_rts_converter0_pl_event', channelID), ...
            'IsRequired',          false ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 RTS Clear Over Range out', channelID), ...
            'InterfaceType',       'OUT', ...
            'PortName',            sprintf('adc%d_clear_or', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_rts_converter01_clear_or', channelID), ...
            'IsRequired',          false ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 RTS Over Range in', channelID), ...
            'InterfaceType',       'IN', ...
            'PortName',            sprintf('adc%d_01_over_range', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_rts_converter01_over_range', channelID), ...
            'IsRequired',          false ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 RTS Over Threshold 1 in', channelID), ...
            'InterfaceType',       'IN', ...
            'PortName',            sprintf('adc%d_01_over_threshold1', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_rts_converter01_over_threshold1', channelID), ...
            'IsRequired',          false ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 RTS Over Threshold 2 in', channelID), ...
            'InterfaceType',       'IN', ...
            'PortName',            sprintf('adc%d_01_over_threshold2', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_rts_converter01_over_threshold2', channelID), ...
            'IsRequired',          false ...
            );
        hRD.addInternalIOInterface(...
            'InterfaceID',         sprintf('ADC%d Ch0 RTS Over Voltage in', channelID), ...
            'InterfaceType',       'IN', ...
            'PortName',            sprintf('adc%d_01_over_voltage', channelID), ...
            'PortWidth',           1, ...
            'InterfaceConnection', sprintf('radio/adc%d_rts_converter01_over_voltage', channelID), ...
            'IsRequired',          false ...
            );
    end
end
