function [ipList] = hdlcoder_base_iplist(  )
% All IP modules in the repository folder.

ipList = {...
    'library/amplitude_controller_1.0',...
    'library/binary_latch_counter_1.0',...
    'library/packet_generator_1.0' ...
    'library/AXI4_Stream_Synchonizer_1.0' ...
    };
