function hB = plugin_board()
% Board definition

% Copyright Brian G. Shea (bshea@eng.ucsd.edu)

% Construct board object
hB = hdlcoder.Board;

hB.BoardName    = 'RFSoC 2x2';

% FPGA device information
hB.FPGAVendor   = 'Xilinx';
hB.FPGAFamily   = 'Zynq UltraScale+ RFSoC';
hB.FPGADevice   = 'xczu28dr-ffvg1517-2-e';
hB.FPGAPackage  = '';
hB.FPGASpeed    = '';

% Tool information
hB.SupportedTool = {'Xilinx Vivado'};

% FPGA JTAG chain position
hB.JTAGChainPosition = 2;

%% Add interfaces
% Standard "External Port" interface
hB.addExternalPortInterface( ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

% Custom board external I/O interface

%% User LEDs
hB.addExternalIOInterface( ...
    'InterfaceID',    'LEDs General Purpose', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'USERLEDs', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'AR12', 'AT12', 'AV12', 'AU12'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

%% User RGB LED 0
hB.addExternalIOInterface( ...
    'InterfaceID',    'RGB LED0', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'RGB_LED0', ...
    'PortWidth',      3, ...
    'FPGAPin',        {'AV11', 'AT11', 'AW11'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

%% User RGB LED 1
hB.addExternalIOInterface( ...
    'InterfaceID',    'RGB LED1', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'RGB_LED1', ...
    'PortWidth',      3, ...
    'FPGAPin',        {'AN13', 'AN12', 'AR11'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});


%% User DIP Swicthes on S1
hB.addExternalIOInterface( ...
    'InterfaceID',    'DIP Switches', ...
    'InterfaceType',  'IN', ...
    'PortName',       'DIPSwitches', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'AT10', 'AU10', 'AV10', 'AW10'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

%% User Push Buttons
hB.addExternalIOInterface( ...
    'InterfaceID',    'User Push Buttons', ...
    'InterfaceType',  'IN', ...
    'PortName',       'PushButtons', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'AM7', 'AM8', 'AN8', 'AP8'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

%% User Reset Push Buttons
hB.addExternalIOInterface( ...
    'InterfaceID',    'Reset Push Buttons', ...
    'InterfaceType',  'IN', ...
    'PortName',       'ResetPushButtons', ...
    'PortWidth',      1, ...
    'FPGAPin',        {'AP9'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

%% Pmod0 Interface
hB.addExternalIOInterface( ...
    'InterfaceID',    'Pmod0 Connector J23', ...
    'InterfaceType',  'INOUT', ...
    'PortName',       'PmodJ32', ...
    'PortWidth',      8, ...
    'FPGAPin',        {'AT16', 'AW15', 'AV16', 'AU15', 'AV13', 'AU13', 'AU14', 'AU15'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});

%% Pmod1 Interface
hB.addExternalIOInterface( ...
    'InterfaceID',    'Pmod Connector J22', ...
    'InterfaceType',  'INOUT', ...
    'PortName',       'PmodJ22', ...
    'PortWidth',      8, ...
    'FPGAPin',        {'AJ15', 'AL15', 'AJ16', 'AK16', 'AM17', 'AP15', 'AL16', 'AK17'}, ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS18'});


% LocalWords:  Zynq xc IOSTANDARD LVCMOS GPLE Pmod INOUT JB DIP
