% Customize DAC Channel
%
% Copyright Brian G. Shea (bshea@eng.ucsd.edu)

function customize(hRD, channelID, config)
% hRD: current reference design registration object
% config: custom parameters of the current channel, in struct format

if(nargin ~= 3)
    error("Invalid number of parameters.")
end

if(config.Enabled)
    if(config.MasterEn && config.SlaveEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('DAC%d RE', channelID),...
            'MasterChannelConnection',  sprintf('rfdc/s%d0_axis', channelID), ...
            'MasterChannelDataWidth',   128, ...    
            'SlaveChannelConnection' ,  sprintf('transmitter/S%d0_AXIS', cahnnelID), ...
            'SlaveChannelDataWidth',    config.SlaveWidth);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('DAC%d IM', channelID),...
            'MasterChannelConnection',  sprintf('rfdc/S%d1_axis', channelID), ...
            'MasterChannelDataWidth',    128, ...
            'SlaveChannelConnection' ,  sprintf('transmitter/S%d1_AXIS', channelID), ...
            'SlaveChannelDataWidth',    config.SlaveWidth);
    elseif (config.SlaveEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('DAC%d RE', channelID),...
            'SlaveChannelConnection' ,  sprintf('transmitter/S%d0_AXIS', cahnnelID), ...
            'SlaveChannelDataWidth',    config.SlaveWidth);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('DAC%d IM', channelID),...
            'SlaveChannelConnection' ,  sprintf('transmitter/S%d1_AXIS', channelID), ...
            'SlaveChannelDataWidth',    config.SlaveWidth);
    elseif (config.MasterEn)
        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('DAC%d RE', channelID),...
            'MasterChannelConnection',  sprintf('rfdc/s%d0_axis', channelID), ...
            'MasterChannelDataWidth',   128);

        hRD.addAXI4StreamInterface(...
            'InterfaceID',              sprintf('DAC%d IM', channelID),...
            'MasterChannelConnection',  sprintf('rfdc/S%d1_axis', channelID), ...
            'MasterChannelDataWidth',    128);
    end 
end